# DOCS
# https://hub.docker.com/_/mariadb

version: '3.1'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password_example
      #MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      #MARIADB_RANDOM_ROOT_PASSWORD: yes
      #MARIADB_ROOT_HOST: "%" # https://mariadb.com/kb/en/create-user/#host-name-component
      MARIADB_DATABASE: example_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      #MARIADB_ROOT_PASSWORD_FILE:/run/secrets/mysql-root